#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Git Projects
  hosts: Ubuntu
  sudo: False
  tasks:
    - name: Make bin Directory
      file: path=/home/vagrant/bin state=directory mode=0755
    - name: Install Git
      apt: name=git state=present
    - name: Pull Down Docker Containers
      git: repo=https://github.com/kurron/docker-compose-tl.git dest=/home/vagrant/bin/servers
    - name: Set permissions on the home directory
      file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

- name: Docker Registry (must be on VPN)
  hosts: Ubuntu
  sudo: True
  tasks:
      - name: Create CA certificates directory
        file: path=/usr/local/share/ca-certificates/docker-registry state=directory
      - name: Create SSL certificates directory
        file: path=/etc/ssl/certs/ state=directory
      - name: Create SSL certificates directory
        get_url: >
                url=http://192.168.254.81:81/artifactory/static/ease/docker-registry/certifcate/registry.transparent.CA.crt
                dest=/usr/local/share/ca-certificates/docker-registry/registry.transparent.CA.crt
        register: certificate
      - name: Add registry to hosts file
        lineinfile: dest=/etc/hosts line="192.168.254.90 registry.transparent.com"
      - name: Add cd1 to hosts file
        lineinfile: dest=/etc/hosts line="192.168.254.81 cd1"
      - name: Update certificates
        shell: update-ca-certificates
        when: certificate|changed
      - name: Place configuration file into the root account
        get_url: url=http://192.168.254.81:81/artifactory/static/ease/docker-registry/.dockercfg dest=/root/.dockercfg
      - name: Place configuration file into the vagrant account
        get_url: url=http://192.168.254.81:81/artifactory/static/ease/docker-registry/.dockercfg dest=/home/vagrant/.dockercfg
      - name: Restart Docker
        command: service docker restart
        when: certificate|changed
      - name: Set permissions on the home directory
        file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

- name: Create Source Folders 
  hosts: Ubuntu
  sudo: False
  tasks:
      - name: Create Asgard project directory
        file: path=/home/vagrant/Stash/Asgard state=directory
      - name: Create Gradle project directory
        file: path=/home/vagrant/Stash/Gradle state=directory
      - name: Create Mold-E project directory
        file: path=/home/vagrant/Stash/Mold-E state=directory
      - name: Create Sush-E project directory
        file: path=/home/vagrant/Stash/Sush-E state=directory
      - name: Set permissions on the home directory
        file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory
