#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Git Projects
  hosts: Ubuntu
  sudo: False
  tasks:
    - name: Make bin Directory
      file: path=/home/vagrant/bin state=directory mode=0755
    - name: Install Git
      apt: name=git state=present
    - name: Pull Down Docker Containers
      git: repo=https://github.com/kurron/docker-compose-tl.git dest=/home/vagrant/bin/servers
    - name: Set permissions on the home directory
      file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

- name: Docker Registry (must be on VPN)
  hosts: Ubuntu
  sudo: True
  tasks:
      - name: Create CA certificates directory
        file: path=/usr/local/share/ca-certificates/docker-registry state=directory
      - name: Create SSL certificates directory
        file: path=/etc/ssl/certs/ state=directory
      - name: Create SSL certificates directory
        get_url: >
                url=http://192.168.254.81:81/artifactory/static/ease/docker-registry/certifcate/registry.transparent.CA.crt
                dest=/usr/local/share/ca-certificates/docker-registry/registry.transparent.CA.crt
        register: certificate
      - name: Add registry to hosts file
        lineinfile: dest=/etc/hosts line="192.168.254.90 registry.transparent.com"
      - name: Add cd1 to hosts file
        lineinfile: dest=/etc/hosts line="192.168.254.81 cd1"
      - name: Update certificates
        shell: update-ca-certificates
        when: certificate|changed
      - name: Place configuration file into the root account
        get_url: url=http://192.168.254.81:81/artifactory/static/ease/docker-registry/.dockercfg dest=/root/.dockercfg
      - name: Place configuration file into the vagrant account
        get_url: url=http://192.168.254.81:81/artifactory/static/ease/docker-registry/.dockercfg dest=/home/vagrant/.dockercfg
      - name: Restart Docker
        command: service docker restart
        when: certificate|changed
      - name: Set permissions on the home directory
        file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

- name: Create Source Folders 
  hosts: Ubuntu
  sudo: False
  tasks:
      - name: Create Asgard project directory
        file: path=/home/vagrant/Stash/Asgard state=directory
      - name: Create Gradle project directory
        file: path=/home/vagrant/Stash/Gradle state=directory
      - name: Create Mold-E project directory
        file: path=/home/vagrant/Stash/Mold-E state=directory
      - name: Create Sush-E project directory
        file: path=/home/vagrant/Stash/Sush-E state=directory
      - name: Create Operations project directory
        file: path=/home/vagrant/Stash/Operations state=directory
      - name: Create Asgard Lite project directory
        file: path=/home/vagrant/Stash/Asgard-Light state=directory
      - name: Set permissions on the home directory
        file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

- name: Update Hosts File
  hosts: Ubuntu
  sudo: True
  tasks:
      - name: Add lds to hostfile
        lineinfile: dest=/etc/hosts line="192.168.100.134 lds"
      - name: Add logfaces to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.123 logfaces"
      - name: Add logfaces-boston to hostfile
        lineinfile: dest=/etc/hosts line="192.168.100.124 logfaces-boston"
      - name: Add mli-forever to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.66 mli-forever"
      - name: Add mongo1test to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.57 mongo1test"
      - name: Add mongo2test to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.63 mongo2test"
      - name: Add mongo3test to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.59 mongo3test" state=absent
      - name: Add stagetwo to hostfile
        lineinfile: dest=/etc/hosts line="192.168.255.29 stagetwo"
      - name: Add cd0 to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.85 cd0"
      - name: Add cd1 to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.81 cd1"
      - name: Add cd5 to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.114 cd5"
      - name: Add cd6 to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.59 cd6"
      - name: Add rabbit-test to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.28 rabbit-test"
      - name: Add docker1test to hostfile
        lineinfile: dest=/etc/hosts line="192.168.254.58 docker1test"
      - name: Add docker1test to hostfile
        lineinfile: dest=/etc/hosts line="192.168.255.18 al-autotest-integration"
